  #key:(空格)v :表示一对键值对（空格一定要有）
  #以空格的缩进来表示层级关系，只要是左对齐的一列数据，都是统一层级的
  #属性和值是大小写敏感的
#  person:
#    last-name: '天\n龙'
#    age: 33
#    boss: false
#    birth: 2018/08/08
#    maps: {k1: val01,k2: val02}
#    lists:
#      - a
#      - b
#    dog:
#      name: 狗
#      age: 2